language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist && make coverage && vendor/bin/phpstan analyze -l 7 src/ tests/

after_script:
  - php vendor/bin/coveralls -v
